### ISSUE TITLE
db: переделать модели и таблички

### ISSUE THREAD

**Issue by xvlady** [xvlady/WoG#9]
Переделать модели и таблички на канонические, 
https://laravel.com/docs/5.2/eloquent
User -это не таблица
должно быть users - таблица, объект User, ссылка на множество зависимых teams(), на зависимое parent()
userId - это не поле. Поле user_id.

**Comment by xVlady** [comment]
Как вариант - взять за основу http://labs.infyom.com/laravelgenerator/docs/installation
или хотябы https://github.com/ignasbernotas/laravel-model-generator

**Comment by xVlady** [comment]
https://backpackforlaravel.com/ - как вообще относиться к готовым формам?

**Comment by xVlady** [comment]
https://github.com/krlove/eloquent-model-generator - больше всего понравился

**Comment by xVlady** [comment]
А это генерация миграций по базе https://github.com/Xethron/migrations-generator

**Comment by xVlady** [comment]
https://github.com/ignasbernotas/laravel-model-generator - ничего не делает
https://github.com/krlove/eloquent-model-generator - не понимает префиксы. Попробую немного допилить.
